### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by simPod** [skrz/bunny-bundle#11]
Hey, I'd like to ask about the status of this repo and the will of your company to further develop this.

There are rotten issues here https://github.com/skrz/bunny-bundle/issues/7 https://github.com/skrz/bunny-bundle/issues/8 and TBH my experience with reaction time on PR I recently submitted was not the best.

I need working bundle so the purpose of this question is to find out whether there's any point in sending more PRs or whether I should further develop fork of this as I don't see any reason to contribute to abandoned repository.

Thanks!

**Comment by mzstic** [comment]
Hi,
sorry for long reaction time with your recent PR. Unfortunately we really didn't have any spare time before christmas...
We're definitely open for new PRs and I'll try to handle them faster. Thanks for mentioning the rotten issues, I'll try to have a look at it in next few days. Everything works for us and nobody reminded these issues in past seven months or so (so probably nobody needed them...) So I kinda forgot about them.

Hope that's what you wanted to hear.

**Comment by Majkl578** [comment]
> Everything works for us and nobody reminded these issues in past seven months or so (so probably nobody needed them...)

Please...
After weeks of waiting for any response we could've been waiting another 7 or more months. And bumping issues is not polite. Instead we had to fork it and fix ourselves: https://github.com/Majkl578/bunny-bundle/commits/dev
I can send those as separate PRs if you won't pass over them. 💯
